# Generated by Django 5.2.9 on 2026-01-05 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('ca_created', 'CA Created'), ('ca_updated', 'CA Updated'), ('cert_issued', 'Certificate Issued'), ('cert_revoked', 'Certificate Revoked'), ('cert_downloaded', 'Certificate Downloaded'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], db_index=True, max_length=30)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name for this CA', max_length=255)),
                ('common_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('organizational_unit', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(help_text='Two-letter country code', max_length=2)),
                ('state', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('key_algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ecdsa', 'ECDSA')], default='rsa', max_length=10)),
                ('key_size', models.IntegerField(default=4096, help_text='Key size in bits (RSA: 2048, 4096; ECDSA: 256, 384)')),
                ('validity_years', models.IntegerField(default=10)),
                ('certificate_pem', models.TextField(blank=True)),
                ('private_key_pem_encrypted', models.TextField(blank=True)),
                ('public_key_pem', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('server_tls', 'Server TLS'), ('client_auth', 'Client Authentication')], default='server_tls', max_length=20)),
                ('common_name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('san_dns_names', models.JSONField(blank=True, default=list)),
                ('san_ip_addresses', models.JSONField(blank=True, default=list)),
                ('san_email_addresses', models.JSONField(blank=True, default=list)),
                ('key_algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ecdsa', 'ECDSA')], default='rsa', max_length=10)),
                ('key_size', models.IntegerField(default=2048)),
                ('validity_days', models.IntegerField(default=365)),
                ('certificate_pem', models.TextField(blank=True)),
                ('private_key_pem_encrypted', models.TextField(blank=True, help_text='Only stored for server-generated keys')),
                ('public_key_pem', models.TextField(blank=True)),
                ('csr_pem', models.TextField(blank=True, help_text='Original CSR if user-submitted')),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('key_compromise', 'Key Compromise'), ('ca_compromise', 'CA Compromise'), ('affiliation_changed', 'Affiliation Changed'), ('superseded', 'Superseded'), ('cessation_of_operation', 'Cessation of Operation'), ('certificate_hold', 'Certificate Hold'), ('privilege_withdrawn', 'Privilege Withdrawn')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_certificates', to=settings.AUTH_USER_MODEL)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='core.certificateauthority')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
