# Generated by Django 5.2.9 on 2026-01-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='crl_der',
            field=models.BinaryField(blank=True, help_text='Cached CRL in DER format', null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='crl_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='crl_next_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='crl_pem',
            field=models.TextField(blank=True, help_text='Cached CRL in PEM format'),
        ),
    ]
