# Generated by Django 5.2.9 on 2026-01-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_crl_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfssl_auto_start', models.BooleanField(default=True, help_text='Automatically start CFSSL when the application starts')),
                ('cfssl_binary_path', models.CharField(blank=True, help_text='Path to CFSSL binary (leave empty for auto-detection)', max_length=500)),
                ('cfssl_host', models.CharField(default='localhost', help_text='Host for CFSSL to bind to', max_length=255)),
                ('cfssl_port', models.PositiveIntegerField(default=8888, help_text='Port for CFSSL to listen on')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
