# Generated by Django 5.2.9 on 2026-01-06 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_app_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='ca_type',
            field=models.CharField(choices=[('root', 'Root CA'), ('intermediate', 'Intermediate CA')], default='root', help_text='Whether this is a root or intermediate CA', max_length=20),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='csr_pem',
            field=models.TextField(blank=True, help_text='CSR for pending intermediates awaiting external signing'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='key_removed_at',
            field=models.DateTimeField(blank=True, help_text='When the private key was removed for air-gapping', null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='key_removed_by',
            field=models.ForeignKey(blank=True, help_text='User who removed the private key', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airgapped_cas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Parent CA that signed this CA's certificate", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.certificateauthority'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='path_length',
            field=models.IntegerField(blank=True, help_text='Maximum CA path length constraint (0 = can only sign end-entity certs)', null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('air_gapped', 'Air-Gapped (Key Removed)'), ('pending', 'Pending (Awaiting Certificate)'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ca_created', 'CA Created'), ('ca_updated', 'CA Updated'), ('intermediate_created', 'Intermediate CA Created'), ('ca_key_exported', 'CA Key Exported'), ('ca_key_removed', 'CA Key Removed (Air-Gapped)'), ('ca_key_restored', 'CA Key Restored'), ('ca_csr_generated', 'CA CSR Generated'), ('ca_cert_imported', 'CA Certificate Imported'), ('cert_issued', 'Certificate Issued'), ('cert_revoked', 'Certificate Revoked'), ('cert_downloaded', 'Certificate Downloaded'), ('user_login', 'User Login'), ('user_logout', 'User Logout')], db_index=True, max_length=30),
        ),
    ]
