# Generated by Django 5.2.9 on 2026-01-06 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_intermediate_ca_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Profile name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when to use this profile')),
                ('is_builtin', models.BooleanField(default=False)),
                ('certificate_type', models.CharField(choices=[('server_tls', 'Server TLS'), ('client_auth', 'Client Authentication')], default='server_tls', max_length=50)),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='Default certificate validity in days')),
                ('key_algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ecdsa', 'ECDSA')], default='rsa', max_length=10)),
                ('key_size', models.PositiveIntegerField(default=2048, help_text='Key size in bits (RSA: 2048/4096, ECDSA: 256/384)')),
                ('organization', models.CharField(blank=True, help_text='Default organization (leave empty to inherit from CA)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_builtin', 'name'],
            },
        ),
    ]
