# Generated by Django 5.2.9 on 2026-01-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_builtin_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ca_created', 'CA Created'), ('ca_updated', 'CA Updated'), ('intermediate_created', 'Intermediate CA Created'), ('ca_key_exported', 'CA Key Exported'), ('ca_key_removed', 'CA Key Removed (Air-Gapped)'), ('ca_key_restored', 'CA Key Restored'), ('ca_csr_generated', 'CA CSR Generated'), ('ca_cert_imported', 'CA Certificate Imported'), ('cert_issued', 'Certificate Issued'), ('cert_revoked', 'Certificate Revoked'), ('cert_downloaded', 'Certificate Downloaded'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored')], db_index=True, max_length=30),
        ),
    ]
