# Generated by Django 5.2.9 on 2026-01-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_certificate_pem',
            field=models.TextField(blank=True, help_text='OCSP signing certificate (delegated responder)'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_not_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_not_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_private_key_pem_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted OCSP signing private key'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_responder_url',
            field=models.URLField(blank=True, help_text='URL of the OCSP responder for this CA (included in issued certificates)'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='ocsp_serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
