# Generated by Django 5.2.9 on 2026-01-12 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_ocsp_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ca_created', 'CA Created'), ('ca_updated', 'CA Updated'), ('intermediate_created', 'Intermediate CA Created'), ('ca_key_exported', 'CA Key Exported'), ('ca_key_removed', 'CA Key Removed (Air-Gapped)'), ('ca_key_restored', 'CA Key Restored'), ('ca_csr_generated', 'CA CSR Generated'), ('ca_cert_imported', 'CA Certificate Imported'), ('cert_issued', 'Certificate Issued'), ('cert_revoked', 'Certificate Revoked'), ('cert_downloaded', 'Certificate Downloaded'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('cert_request_submitted', 'Certificate Request Submitted'), ('cert_request_approved', 'Certificate Request Approved'), ('cert_request_rejected', 'Certificate Request Rejected')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='PendingCertificateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('server_tls', 'Server TLS'), ('client_auth', 'Client Authentication')], default='server_tls', help_text='Type of certificate requested', max_length=20)),
                ('common_name', models.CharField(max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('san_dns_names', models.JSONField(blank=True, default=list, help_text='DNS names to include in certificate')),
                ('san_ip_addresses', models.JSONField(blank=True, default=list, help_text='IP addresses to include in certificate')),
                ('san_email_addresses', models.JSONField(blank=True, default=list, help_text='Email addresses to include in certificate')),
                ('key_algorithm', models.CharField(choices=[('rsa', 'RSA'), ('ecdsa', 'ECDSA')], default='rsa', max_length=10)),
                ('key_size', models.IntegerField(default=2048, help_text='Key size in bits')),
                ('validity_days', models.IntegerField(default=365, help_text='Requested certificate validity in days')),
                ('csr_pem', models.TextField(help_text='Certificate Signing Request in PEM format')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('ca', models.ForeignKey(help_text='CA that will sign this certificate', on_delete=django.db.models.deletion.PROTECT, related_name='pending_requests', to='core.certificateauthority')),
                ('issued_certificate', models.ForeignKey(blank=True, help_text='Certificate that was issued from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='core.certificate')),
                ('requested_by', models.ForeignKey(help_text='User who requested the certificate', on_delete=django.db.models.deletion.PROTECT, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who approved or rejected the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Certificate Request',
                'verbose_name_plural': 'Pending Certificate Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
