# Generated by Django 5.2.9 on 2026-01-12 23:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def set_default_expiration_days(apps, schema_editor):
    """Set default expiration warning days for existing AppSettings."""
    AppSettings = apps.get_model('core', 'AppSettings')
    for settings_obj in AppSettings.objects.all():
        if not settings_obj.expiration_warning_days:
            settings_obj.expiration_warning_days = [30, 14, 7]
            settings_obj.save(update_fields=['expiration_warning_days'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action_pendingcertificaterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='email_backend',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('sendgrid', 'SendGrid API'), ('mailgun', 'Mailgun API'), ('ses', 'AWS SES')], default='smtp', help_text='Email service to use', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Enable email notifications'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='email_from_address',
            field=models.EmailField(blank=True, default='', help_text='Email address to send notifications from (e.g., pki@example.com)', max_length=254),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='Pemly PKI', help_text='Display name for emails', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='expiration_warning_days',
            field=models.JSONField(blank=True, default=list, help_text='Days before expiration to send warnings (e.g., [30, 14, 7])'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mailgun_api_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted Mailgun API key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mailgun_domain',
            field=models.CharField(blank=True, default='', help_text='Mailgun domain (e.g., mg.example.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mailgun_region',
            field=models.CharField(choices=[('us', 'US'), ('eu', 'EU')], default='us', help_text='Mailgun region', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notify_expiration_warnings',
            field=models.BooleanField(default=True, help_text='Send certificate expiration warnings'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notify_on_certificate_revoked',
            field=models.BooleanField(default=True, help_text='Notify certificate owner when their certificate is revoked'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notify_on_request_approved',
            field=models.BooleanField(default=True, help_text='Notify requester when their request is approved'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notify_on_request_rejected',
            field=models.BooleanField(default=True, help_text='Notify requester when their request is rejected'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notify_on_request_submitted',
            field=models.BooleanField(default=True, help_text='Notify managers when new certificate request is submitted'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='sendgrid_api_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted SendGrid API key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ses_access_key_id_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted AWS access key ID'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ses_region',
            field=models.CharField(blank=True, default='us-east-1', help_text='AWS region (e.g., us-east-1)', max_length=50),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ses_secret_access_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted AWS secret access key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='SMTP server hostname', max_length=255),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted SMTP password'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP server port (usually 587 for TLS, 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL encryption'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', help_text='SMTP authentication username', max_length=255),
        ),
        migrations.CreateModel(
            name='ExpirationWarningLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warning_threshold', models.IntegerField(help_text='Days before expiration when this warning was sent')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_warnings', to='core.certificate')),
                ('sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_expiration_warnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expiration Warning Log',
                'verbose_name_plural': 'Expiration Warning Logs',
                'ordering': ['-sent_at'],
                'unique_together': {('certificate', 'warning_threshold')},
            },
        ),
        migrations.RunPython(set_default_expiration_days),
    ]
