# Generated by Django 5.2.9 on 2026-01-13 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appsettings_email_backend_appsettings_email_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this certificate has been archived'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ca_created', 'CA Created'), ('ca_updated', 'CA Updated'), ('intermediate_created', 'Intermediate CA Created'), ('ca_key_exported', 'CA Key Exported'), ('ca_key_removed', 'CA Key Removed (Air-Gapped)'), ('ca_key_restored', 'CA Key Restored'), ('ca_csr_generated', 'CA CSR Generated'), ('ca_cert_imported', 'CA Certificate Imported'), ('cert_issued', 'Certificate Issued'), ('cert_revoked', 'Certificate Revoked'), ('cert_archived', 'Certificate Archived'), ('cert_unarchived', 'Certificate Unarchived'), ('cert_downloaded', 'Certificate Downloaded'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('cert_request_submitted', 'Certificate Request Submitted'), ('cert_request_approved', 'Certificate Request Approved'), ('cert_request_rejected', 'Certificate Request Rejected')], db_index=True, max_length=30),
        ),
    ]
