# Generated by Django 5.2.9 on 2026-01-13 03:38

from django.db import migrations


def create_default_profiles(apps, schema_editor):
    """Create default certificate profiles for new certificate types."""
    CertificateProfile = apps.get_model('core', 'CertificateProfile')

    # Email Protection Profile
    CertificateProfile.objects.get_or_create(
        name='Email Protection (S/MIME)',
        defaults={
            'description': 'For securing email communications with S/MIME. '
                          'Use this for employee email certificates to sign and encrypt messages. '
                          'Recipients must import your CA certificate to verify signatures.',
            'is_builtin': True,
            'certificate_type': 'email_protection',
            'validity_days': 365,  # 1 year
            'key_algorithm': 'rsa',
            'key_size': 2048,
            'organization': '',
        }
    )

    # Document Signing Profile
    CertificateProfile.objects.get_or_create(
        name='Document Signing',
        defaults={
            'description': 'For digitally signing PDF documents and other files. '
                          'Use this for internal document workflows, contracts, and approvals. '
                          'Works with Adobe Acrobat and other PDF signing tools.',
            'is_builtin': True,
            'certificate_type': 'document_signing',
            'validity_days': 730,  # 2 years
            'key_algorithm': 'rsa',
            'key_size': 2048,
            'organization': '',
        }
    )


def remove_default_profiles(apps, schema_editor):
    """Remove default profiles if migration is reversed."""
    CertificateProfile = apps.get_model('core', 'CertificateProfile')
    CertificateProfile.objects.filter(
        name__in=['Email Protection (S/MIME)', 'Document Signing'],
        is_builtin=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_email_and_document_signing_cert_types'),
    ]

    operations = [
        migrations.RunPython(create_default_profiles, remove_default_profiles),
    ]
