# Generated by Django 5.2.9 on 2026-01-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_default_email_document_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('server_tls', 'Server TLS'), ('client_auth', 'Client Authentication'), ('email_protection', 'Email Protection (S/MIME)'), ('document_signing', 'Document Signing'), ('user_authentication', 'User Authentication (Smart Card/PIV)')], default='server_tls', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificateprofile',
            name='certificate_type',
            field=models.CharField(choices=[('server_tls', 'Server TLS'), ('client_auth', 'Client Authentication'), ('email_protection', 'Email Protection (S/MIME)'), ('document_signing', 'Document Signing'), ('user_authentication', 'User Authentication (Smart Card/PIV)')], default='server_tls', max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingcertificaterequest',
            name='type',
            field=models.CharField(choices=[('server_tls', 'Server TLS'), ('client_auth', 'Client Authentication'), ('email_protection', 'Email Protection (S/MIME)'), ('document_signing', 'Document Signing'), ('user_authentication', 'User Authentication (Smart Card/PIV)')], default='server_tls', help_text='Type of certificate requested', max_length=20),
        ),
    ]
