# Generated by Django 5.2.9 on 2026-01-13 03:47

from django.db import migrations


def create_user_auth_profile(apps, schema_editor):
    """Create default certificate profile for user authentication."""
    CertificateProfile = apps.get_model('core', 'CertificateProfile')

    # User Authentication Profile
    CertificateProfile.objects.get_or_create(
        name='User Authentication (Smart Card/PIV)',
        defaults={
            'description': 'For user authentication with smart cards, YubiKeys, or PIV tokens. '
                          'Use this for Windows domain login, VPN authentication, and physical access control. '
                          'Requires deployment of your CA certificate to client systems via GPO or MDM.',
            'is_builtin': True,
            'certificate_type': 'user_authentication',
            'validity_days': 730,  # 2 years
            'key_algorithm': 'rsa',
            'key_size': 2048,
            'organization': '',
        }
    )


def remove_user_auth_profile(apps, schema_editor):
    """Remove user authentication profile if migration is reversed."""
    CertificateProfile = apps.get_model('core', 'CertificateProfile')
    CertificateProfile.objects.filter(
        name='User Authentication (Smart Card/PIV)',
        is_builtin=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_user_authentication_cert_type'),
    ]

    operations = [
        migrations.RunPython(create_user_auth_profile, remove_user_auth_profile),
    ]
