# Generated by Django 5.2.9 on 2026-01-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_default_user_auth_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='email_from_name',
            field=models.CharField(blank=True, default='PEMLY PKI', help_text='Display name for emails', max_length=255),
        ),
    ]
