# Generated by Django 5.2.9 on 2026-01-13 04:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_appsettings_email_from_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('prefix', models.CharField(editable=False, help_text='Short prefix for key identification (visible)', max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, help_text='Hashed API key for secure storage', max_length=128)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this key', null=True)),
                ('user', models.ForeignKey(help_text='User associated with this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
