# Generated by Django 5.2.17 on 2026-09-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ca_created', 'CA Created'), ('ca_updated', 'CA Updated'), ('intermediate_created', 'Intermediate CA Created'), ('ca_key_exported', 'CA Key Exported'), ('ca_key_removed', 'CA Key Removed (Air-Gapped)'), ('ca_key_restored', 'CA Key Restored'), ('ca_csr_generated', 'CA CSR Generated'), ('ca_cert_imported', 'CA Certificate Imported'), ('ca_deleted', 'CA Deleted'), ('cert_issued', 'Certificate Issued'), ('cert_revoked', 'Certificate Revoked'), ('cert_renewed', 'Certificate Renewed'), ('cert_archived', 'Certificate Archived'), ('cert_unarchived', 'Certificate Unarchived'), ('cert_downloaded', 'Certificate Downloaded'), ('user_login', 'User Login'), ('user_login_failed', 'User Login Failed'), ('user_login_blocked', 'User Login Blocked (Throttled)'), ('api_key_auth_failed', 'API Key Authentication Failed'), ('user_logout', 'User Logout'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_role_changed', 'User Role Changed'), ('cert_request_submitted', 'Certificate Request Submitted'), ('cert_request_approved', 'Certificate Request Approved'), ('cert_request_rejected', 'Certificate Request Rejected'), ('api_key_created', 'API Key Created'), ('api_key_deleted', 'API Key Deleted')], db_index=True, max_length=30),
        ),
    ]
