# Generated by Django 5.2.9 on 2026-01-12 20:00

from django.db import migrations


def assign_roles_to_existing_users(apps, schema_editor):
    """
    Assign roles to existing users who don't have UserProfile instances.

    Logic:
    - First 2 superusers → Super Admin
    - Additional superusers → Administrator
    - Regular users → Certificate Manager (for backward compatibility with existing setups)
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    # Get all users
    all_users = User.objects.all()
    if not all_users.exists():
        # No existing users, nothing to do
        return

    super_admin_count = 0

    for user in all_users:
        # Skip if user already has a profile (created by signal)
        if UserProfile.objects.filter(user=user).exists():
            continue

        # Determine role
        if user.is_superuser:
            # First 2 superusers become Super Admin
            if super_admin_count < 2:
                role = 'super_admin'
                super_admin_count += 1
            else:
                role = 'administrator'
        else:
            # Regular users become Certificate Managers for backward compatibility
            # This ensures existing systems continue to work after upgrade
            role = 'certificate_manager'

        # Create profile
        UserProfile.objects.create(user=user, role=role)


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - delete all UserProfiles.

    Note: This will be destructive if run on a production system.
    """
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '__latest__'),  # Ensure User model is available
    ]

    operations = [
        migrations.RunPython(
            assign_roles_to_existing_users,
            reverse_code=reverse_migration
        ),
    ]
